# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1109, 520)
        self.tW_StockInformation = QtWidgets.QTableWidget(Form)
        self.tW_StockInformation.setGeometry(QtCore.QRect(10, 50, 1091, 461))
        self.tW_StockInformation.setObjectName("tW_StockInformation")
        self.tW_StockInformation.setColumnCount(0)
        self.tW_StockInformation.setRowCount(0)
        self.btn_Scrapy = QtWidgets.QPushButton(Form)
        self.btn_Scrapy.setGeometry(QtCore.QRect(10, 10, 121, 31))
        self.btn_Scrapy.setObjectName("btn_Scrapy")
        self.txt_Url = QtWidgets.QTextEdit(Form)
        self.txt_Url.setGeometry(QtCore.QRect(190, 10, 721, 31))
        self.txt_Url.setObjectName("txt_Url")
        self.lbl_Url = QtWidgets.QLabel(Form)
        self.lbl_Url.setGeometry(QtCore.QRect(140, 20, 58, 15))
        self.lbl_Url.setObjectName("lbl_Url")
        self.btn_OutputCSV = QtWidgets.QPushButton(Form)
        self.btn_OutputCSV.setGeometry(QtCore.QRect(920, 10, 121, 28))
        self.btn_OutputCSV.setObjectName("btn_OutputCSV")
        self.btn_Folder = QtWidgets.QPushButton(Form)
        self.btn_Folder.setGeometry(QtCore.QRect(1050, 10, 51, 28))
        self.btn_Folder.setText("")
        self.btn_Folder.setObjectName("btn_Folder")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_Scrapy.setText(_translate("Form", "取得股票資料"))
        self.lbl_Url.setText(_translate("Form", "網址:"))
        self.btn_OutputCSV.setText(_translate("Form", "輸出文檔"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
